### ISSUE TITLE
Failing on node 8.0.0

### ISSUE THREAD

**Issue by jfoclpf** [sindresorhus/is-online#56]
Node 8.0.0 is not that ancient and it breaks on the spread syntax for objects (ECMAScript 2018). 
This node version [does not support spread syntax](https://node.green/#ES2018-features-object-rest-spread-properties-object-rest-properties).

We should take care of backward compatibility.

```
/home/travis/build/jfoclpf/autocosts/node_modules/is-online/index.js:22
		...options
		^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/jfoclpf/autocosts/commons.js:105:18)
```

It fails on line 22 of `index.js`

```js
module.exports = options => {
	options = {
		timeout: 5000,
		version: 'v4',
		...options
	};
```

Can't we use `Object.assign` to merge the options?

```js
module.exports = options => {
	options = Object.assign(
		{
			timeout: 5000,
			version: 'v4'
		},
		options || {},
	);
```

I tested and it works

**Comment by sindresorhus** [comment]
> This node version does not support spread syntax.

Yes it does, and the table clearly shows that. You just need to upgrade to a recent 8.x.x version.

**Comment by jfoclpf** [comment]
Ok, thanks, I was checking on node 8.0.0

In your travis you have 

```
node_js:
  - '10'
  - '8'
```

Does it mean the lastest node 8.x.x?
