### ISSUE TITLE
Error in electron

### ISSUE THREAD

**Issue by bhasim1** [sindresorhus/is-online#90]
ERROR:
Uncaught C:\Users\Lennox\Desktop\electron\node_modules\is-online\index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import os from 'node:os';
                                                                                                                                                                  ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
    at Module._compile (internal/modules/cjs/loader.js:712:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at file:///C:/Users/Lennox/Desktop/electron/index.html:97:30

I guess the proplem is that this modules uses es6 import and not require

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
