### ISSUE TITLE
Error: getsockname EBADF

### ISSUE THREAD

**Issue by zach-is-my-name** [sindresorhus/is-online#92]
I don't understand the error, nor why I'm getting it.  The only reason I felt confident opening the issue is because the stack trace begins with is-online and ends with one of it's dependencies, which upon review has not been updated in 2 years... 

```
Error: getsockname EBADF
    at Socket.address (node:dgram:764:11)
    at isListening (/home/zmg/Tinker/wiener/node_modules/dns-socket/index.js:283:19)
    at new DNS (/home/zmg/Tinker/wiener/node_modules/dns-socket/index.js:36:7)
    at DNS (/home/zmg/Tinker/wiener/node_modules/dns-socket/index.js:12:12)
    at queryDns (file:///home/zmg/Tinker/wiener/node_modules/public-ip/index.js:90:17)
    at file:///home/zmg/Tinker/wiener/node_modules/public-ip/index.js:213:22
    at queryAll (file:///home/zmg/Tinker/wiener/node_modules/public-ip/index.js:224:4)
    at publicIp.v4 (file:///home/zmg/Tinker/wiener/node_modules/public-ip/index.js:240:10)
    at file:///home/zmg/Tinker/wiener/node_modules/is-online/index.js:58:48
    at isOnline (file:///home/zmg/Tinker/wiener/node_modules/is-online/index.js:62:5)
```

Here's me calling it if it matters... 

```
import React, {useEffect, useState} from 'react'
import isOnline from 'is-online'
import isReachable from 'is-reachable'

export function useHasInternet() {
  const [hasInternet, setHasInternet] = useState("loading")
  const [wienIsReachable, setWienIsReachable] = useState("loading")
  useEffect(() => {
    (async () => {
      setHasInternet(await isOnline() && await isReachable('https://weekinethereumnews.com') );
    })()
  } );
  
 return hasInternet
}
```
is-online is version 10

edit: related? https://github.com/sindresorhus/is-online/issues/47#issuecomment-602411439
I'm experiencing a core dump as well

**Comment by zach-is-my-name** [comment]
Please ignore.  Above is likely  caused by an unhandled axios error.
